 create TABLE user_info (
    id bigint generated by default as identity,
    active boolean not null,
    age integer not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    username varchar(32) not null,
    primary key (id)
 );

  create TABLE currencys (
    id bigint generated by default as identity,
    valute varchar(3) not null,
    primary key (id)
 );

 create TABLE bill (
    number_card bigint generated by default as identity,
    amoung double not null,
    currency varchar(3) not null,
    user_id bigint,
    primary key (number_card),
    foreign key (user_id) references user_info(id),
    foreign key (currency) references currencys(valute)
 );

 create TABLE rates (
    id bigint generated by default as identity,
    coefficient double not null,
    first varchar not null,
    second varchar not null,
    primary key (id),
    foreign key (first) references currencys(valute),
    foreign key (second) references currencys(valute)
 );
 create TABLE transaction (
    id bigint generated by default as identity,
    message varchar(255),
    user bigint,
    bill bigint,
    foreign key (user) references user_info(id),
    foreign key (bill) references bill(number_card),
    primary key (id)
 );

 create TABLE user_role (
    user_id bigint not null,
    roles varchar(255),
    foreign key (user_id) references user_info(id)
 );
