 drop table bill if exists;
 drop table currencys if exists;
 drop table rates if exists;
 drop table transaction if exists;
 drop table user_info if exists;
 drop table user_role if exists;

 CREATE TABLE bill (
    number_card bigint generated by default as identity,
    amoung double not null,
    currency_valute varchar(3) not null,
    user_id_id bigint,
    primary key (number_card)
 );
 CREATE TABLE currencys (
    id bigint generated by default as identity,
    valute varchar(3) not null,
    primary key (id)
 );
 CREATE TABLE rates (
    id bigint generated by default as identity,
    x double not null,
    first_valute varchar(3) not null,
    second_valute varchar(3) not null,
    primary key (id)
 );
 CREATE TABLE transaction (
    id bigint generated by default as identity,
    bill_id bigint,
    message varchar(255),
    user_id bigint,
    primary key (id)
 );
 CREATE TABLE user_info (
    id bigint generated by default as identity,
    active boolean not null,
    age integer not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    username varchar(32) not null,
    primary key (id)
 );
 CREATE TABLE user_role (
    user_id bigint not null,
    roles varchar(255)
 );
 alter table bill add constraint currency foreign key (currency_valute) references currencys (valute);
 alter table bill add constraint user_id foreign key (user_id_id) references user_info(id);
 alter table currencys add constraint valutes unique (valute);
 alter table rates add constraint first_currencys foreign key (first_valute) references currencys (valute);
 alter table rates add constraint second_currencys foreign key (second_valute) references currencys (valute);
 alter table user_role add constraint users_id foreign key (user_id) references user_info(id);
